# Generated by Django 4.1 on 2022-08-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.IntegerField(default=0)),
                ('grupo', models.IntegerField(default=0)),
                ('elemento', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=7)),
                ('imagen', models.ImageField(upload_to='articulos/pictures')),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
